### ISSUE TITLE
Evaluation function

### ISSUE THREAD

**Issue by Ezraay** [Ezraay/kaggle#2]
Heuristic function to take in a board and a player's move - return a score indicating how favourable the game is for that player. Doesn't look ahead/assume certain moves will be made.

**Comment by EmreCakmakcioglu** [comment]
Simple eval function which does the following:

(read here for more info: https://roboticsproject.readthedocs.io/en/latest/ConnectFourAlgorithm.html)

- Takes chunks (windows) which are 4 cells long, for each window allocate:
- 100 points for 4 in a row
- 5 points for 3 in a row
- 2 points for 2 in a row
- -4 points for blocking an opponents win (playing defensively is not ideal, your opponent should ideally not be in a position to even have 3 in a row...)
- (3 * tiles) points for how many are in the centre (you want control here).

You can therefore work out which player is ahead by running the eval function twice and subtracting one from the other to get a net result. Currently, if player 1 is ahead, the final result will be a positive number. Negative if player 2 is ahead.

**Comment by JackyZhaoMonash** [comment]
Lisa are taking over for comments and Pull requrest to master

**Comment by Ezraay** [comment]
Fixed with #6
