### ISSUE TITLE
Copy board functionality

### ISSUE THREAD

**Issue by Ezraay** [Ezraay/kaggle#31]
There needs to be ability to copy a board object into a new instance. It should be a smart copy that contains the same history, board state etc. This is required so that agents don't accidentally mess with the actual board state when performing searches incorrectly.
```python
# Example
board = Board()
board.create((7, 6))
board2 = board.copy()
```

**Comment by Q-g2** [comment]
Does this copy() function okay ? 
def copy(self):
    """Create a deep copy of the current board."""
    new_board = Board()
    new_board.__heights = self.__heights.copy()
    new_board.__board = [row.copy() for row in self.__board]
    new_board.__size = self.__size
    new_board.history = self.history.copy()
    return new_board

**Comment by Ezraay** [comment]
@Q-g2 code encounters an error
![image](https://github.com/Ezraay/kaggle/assets/42169797/b94a0ac2-760a-4351-917f-29c3a916d964)
you should make the function a part of the board object, see my initial code snippet for expected usage.
Error is you can't access private members of a class outside code in the class declaration.
![image](https://github.com/Ezraay/kaggle/assets/42169797/ac069f1c-d163-402c-a126-905368605403)
